TARGET=netsim_app
OBJECTS=main.o ztpSender.o ztpReceiver.o ztpPacket.o app_config.o 
LIBRARY=../netsim/libnetsim.a
SOURCES=main.cpp ztpSender.cpp ztpReceiver.cpp ztpPacket.cpp app_config.cpp
CCFLAGS=-g

all: netsim $(TARGET)

netsim:
	(cd ../netsim; make)

$(TARGET): $(OBJECTS) $(LIBRARY)
	g++ $(CCFLAGS) -o $(TARGET) $(OBJECTS) $(LIBRARY)

%.o: %.cpp
	g++ -c $(CCFLAGS) $*.cpp

%.o: %.c
	gcc -c $(CCFLAGS) $*.c

depend: $(SOURCES)
	(cd ../netsim; make depend)
	makedepend $(SOURCES)

clean:
	(cd ../netsim; make clean)
	rm *.o

# DO NOT DELETE

main.o: ../netsim/common.h /usr/include/stdlib.h /usr/include/features.h
main.o: /usr/include/alloca.h ../netsim/Config.h ../netsim/Packet.h
main.o: ../netsim/Timer.h ../netsim/PacketScheduler.h ../netsim/Scheduler.h
main.o: ../netsim/Topology.h /usr/include/unistd.h /usr/include/getopt.h
ztpSender.o: ../netsim/common.h /usr/include/stdlib.h /usr/include/features.h
ztpSender.o: /usr/include/alloca.h ../netsim/Node.h ../netsim/FIFONode.h
ztpSender.o: ../netsim/Packet.h ztpPacket.h ../netsim/Timer.h
ztpSender.o: ../netsim/PacketScheduler.h ../netsim/Scheduler.h ztpSender.h
ztpReceiver.o: ../netsim/common.h /usr/include/stdlib.h
ztpReceiver.o: /usr/include/features.h /usr/include/alloca.h ../netsim/Node.h
ztpReceiver.o: ../netsim/FIFONode.h ../netsim/Packet.h ztpPacket.h
ztpReceiver.o: ../netsim/PacketScheduler.h ../netsim/Timer.h
ztpReceiver.o: ../netsim/Scheduler.h ztpReceiver.h
ztpPacket.o: ../netsim/common.h /usr/include/stdlib.h /usr/include/features.h
ztpPacket.o: /usr/include/alloca.h ../netsim/Node.h ../netsim/FIFONode.h
ztpPacket.o: ../netsim/Packet.h ztpPacket.h ../netsim/Timer.h
ztpPacket.o: ../netsim/PacketScheduler.h ../netsim/Scheduler.h
ztpRouter.o: ../netsim/common.h /usr/include/stdlib.h
ztpRouter.o: /usr/include/features.h /usr/include/alloca.h ../netsim/Node.h
ztpRouter.o: ../netsim/FIFONode.h ../netsim/Packet.h ztpPacket.h
ztpRouter.o: ../netsim/PacketScheduler.h ../netsim/Timer.h
ztpRouter.o: ../netsim/Scheduler.h ztpReceiver.h
ztpHost.o: ../netsim/common.h /usr/include/stdlib.h
ztpHost.o: /usr/include/features.h /usr/include/alloca.h ../netsim/Node.h
ztpHost.o: ../netsim/FIFONode.h ../netsim/Packet.h ztpPacket.h
ztpHost.o: ../netsim/PacketScheduler.h ../netsim/Timer.h
ztpHost.o: ../netsim/Scheduler.h ztpReceiver.h
app_config.o: /usr/include/string.h /usr/include/features.h
app_config.o: /usr/include/xlocale.h ../netsim/common.h /usr/include/stdlib.h
app_config.o: /usr/include/alloca.h ../netsim/Config.h ../netsim/Node.h
app_config.o: ../netsim/FIFONode.h ../netsim/Packet.h ztpHost.h ztpRouter.h
app_config.o: ztpSender.h ztpReceiver.h
